// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PQT.CC.Data;

namespace PQT.CC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180628122934_05")]
    partial class _05
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("PQT.CC.Models.Applicant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AnnualIncome");

                    b.Property<DateTime>("DOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("PQT.CC.Models.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("APR");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("PromotionID");

                    b.HasKey("ID");

                    b.HasIndex("PromotionID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PQT.CC.Models.Promotion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("End");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<DateTime>("Start");

                    b.HasKey("ID");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("PQT.CC.Models.Card", b =>
                {
                    b.HasOne("PQT.CC.Models.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionID");
                });
#pragma warning restore 612, 618
        }
    }
}
